### ISSUE TITLE
Login - Landing Page (Front-End)

### ISSUE THREAD

**Issue by ArkSoftwareStudio** [ArkSoftwareStudio/SeamFlow#12]
### **Creating the Login Page**

![Image](https://github.com/ArkSoftwareStudio/SeamFlow/assets/54995861/b0c43e73-a500-4b96-b05d-25fa966762dc)

**Comment by GauravKukreti** [comment]
Hi 👋
I am happy to contribute if you're open to it.
I have experience in react and tailwind css.
If you need the exact same login page as in this image, i can help you.
Let me know if you're interested.

**Comment by ArkSoftwareStudio** [comment]
Hello! 👋

I appreciate your comment and I will definitely keep it in mind! At the moment this is more of a personal project with a small team of three but we do plan on expanding and when the time comes I'm sure we wi definitely need contributors! 

Thank you!

**Comment by GauravKukreti** [comment]
Thanks for sharing! Best of luck with your project's expansion. Feel free to reach out in the future!
